tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - vscjava.vscode-maven@0.21.2:tFEkt2FqLujaNTLU5AmRiQ==